# Author: Mateus Meyer Jiacomelli
# 
# RS232 commands document:
# https://downloads.dell.com/manuals/all-products/esuprt_display_projector/esuprt_projector/dell-1409x_reference%20guide_en-us.pdf

[general]
manufacturer_name="Dell"
product_name="1409X"
software_version="M0R001"
class_type=2

[connection]
baud_rate=19200

[resolution]
recommended=[1024, 768]

[behavior]
send_on_start = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x46, 0x7e, 0x11, 0x11, 0x01, 0x00, 0xff]
wait_for_response = 75
fake_states = {input = true} # Can only query current source on firmware version M0R002 or greater
quirks = {power_on_is_toggle = true, volume_is_absolute = [0x0, 0x14, 0x01]}

[commands."1POWR".inputs."?"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x46, 0x7e, 0x11, 0x11, 0x01, 0x00, 0xff]
wait_for_response = 100
outputs = [
    {on_received_type="value", on_received=[0x00, 0xff, 0x01], response_type = "value", response_value = "0"},
    {on_received_type="value", on_received=[0x00, 0xff, 0x02], response_type = "value", response_value = "3"},
    {on_received_type="value", on_received=[0x00, 0xff, 0x03], response_type = "value", response_value = "1"},
    {on_received_type="value", on_received=[0x00, 0xff, 0x04], response_type = "value", response_value = "2"},
    {on_received_type="value", on_received=[0x00, 0xff, 0x05], response_type = "value", response_value = "1"}
]

[commands."1POWR".inputs."1"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0xc6, 0xff, 0x11, 0x11, 0x01, 0x00, 0x01]
outputs = [
    {on_received_type="value", on_received=[0x0], response_type = "default", response_value = "OK"}
]

# output on shutdown = Normal shutdown from 2230.
[commands."1POWR".inputs."0"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x0c, 0x3e, 0x11, 0x11, 0x01, 0x00, 0x18]
send_times = 2 # projector asks for shutdown confirmation, needs to trigger twice
outputs = [
    {on_received_type="value", on_received=[0x0], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

# Input RGB 1 (using VGA-1)
[commands."1INPT".inputs."11"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0xcc, 0xff, 0x11, 0x11, 0x01, 0x00, 0x19]
outputs = [
    {on_received_type="value", on_received=[0x0, 0x19], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

# Input RGB 2 (using VGA-2)
[commands."1INPT".inputs."12"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x28, 0xfe, 0x11, 0x11, 0x01, 0x00, 0x69]
outputs = [
    {on_received_type="value", on_received=[0x0, 0x69], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

# Input Video 1 (using Composite)
[commands."1INPT".inputs."21"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0xdf, 0x7f, 0x11, 0x11, 0x01, 0x00, 0x23]
outputs = [
    {on_received_type="value", on_received=[0x0, 0x23], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

# Input Video 2 (using S-Video)
[commands."1INPT".inputs."22"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x1f, 0xbe, 0x11, 0x11, 0x01, 0x00, 0x22]
outputs = [
    {on_received_type="value", on_received=[0x00, 0x22], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

[commands."2FREZ".inputs."1"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x02, 0x7e, 0x11, 0x11, 0x01, 0x00, 0x0f]
outputs = [
    {on_received_type="value", on_received=[0x00, 0x0f], response_type = "default", response_value = "OK"},
    {on_received_type="value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

[commands."2FREZ".inputs."0"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0xed, 0x3f, 0x11, 0x11, 0x01, 0x00, 0x64]
outputs = [
    {on_received_type = "value", on_received=[0x00, 0x64], response_type = "default", response_value = "OK"},
    {on_received_type = "value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

[commands."2FREZ".inputs."?"]
send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0x2d, 0xfe, 0x11, 0x11, 0x01, 0x00, 0x65]
outputs = [
    {on_received_type = "value", on_received=[0x00, 0x65, 0x00], response_type = "value", response_value = "0"},
    {on_received_type = "value", on_received=[0x00, 0x65, 0x01], response_type = "value", response_value = "1"},
    {on_received_type = "value", on_received=[0x01], response_type = "default", response_value = "ERR3"}
]

#[commands."1LAMP".inputs."?"]
#send = [0xbe, 0xef, 0x10, 0x05, 0x00, 0xda, 0x7f, 0x11, 0x11, 0x01, 0x11, 0x2f]
#outputs = [
#    {}
#]